const products = [
    { name: 'Organic Apples', price: 'Ksh30/each', img: 'Images/Organic-apples.jpg', category: 'Fruits & Vegetables' },
    { name: 'Fresh Milk', price: 'Ksh280/gallon', img: 'Images/Fresh-Milk.jpg', category: 'Dairy & Eggs' },
    { name: 'Loaf of Bread', price: 'Ksh120/loaf', img: 'Images/Loaf.jpg', category: 'Bakery' },
    { name: 'Red Tomatoes', price: 'Ksh10/each', img: 'Images/Tomatoes.jpg', category: 'Fruits & Vegetables' },
    { name: 'Beef', price: 'Ksh600/kg', img: 'Images/Beef.jpg', category: 'Meat & Poultry' },
    { name: 'Organic Spinach', price: 'Ksh30/bunch', img: 'Images/Organic-Spinach.jpg', category: 'Fruits & Vegetables' },
    { name: 'Oranges', price: 'Ksh20/each', img: 'Images/Oranges.jpg', category: 'Fruits & Vegetables' },
    { name: 'Watermelon', price: 'Ksh65/kg', img: 'Images/Watermelon.jpg', category: 'Fruits & Vegetables' },
    { name: 'Onions', price: 'Ksh100/kg', img: 'Images/Onions.jpg', category: 'Fruits & Vegetables' },
    { name: 'Whipping Cream', price: 'Ksh700/litre', img: 'Images/Whipping Cream.jpg', category: 'Dairy & Eggs' },
    { name: 'Beetroot Vegetable', price: 'Ksh200/kg', img: 'Images/Beetroot Vegetable.jpg', category: 'Fruits & Vegetables' },
    { name: 'Green Peas', price: 'Ksh250/kg', img: 'Images/Green Peas.jpg', category: 'Fruits & Vegetables' },
    { name: 'Cassava', price: 'Ksh120/kg', img: 'Images/Cassava.jpg', category: 'Fruits & Vegetables' },
    { name: 'Bell Pepper', price: 'Ksh200/kg', img: 'Images/Bell Pepper.jpg', category: 'Fruits & Vegetables' },
    { name: 'Wheat grains', price: 'Ksh55/kg', img: 'Images/Wheat grains.jpg', category: 'Pantry Staples' },
    { name: 'Pinapples', price: 'Ksh150/each', img: 'Images/Pinapples.jpg', category: 'Fruits & Vegetables' },
    { name: 'Cheese', price: 'Ksh1500/kg', img: 'Images/Cheese.jpg', category: 'Dairy & Eggs' },
    { name: 'Bananas', price: 'Ksh120/bunch', img: 'Images/Bananas.jpg', category: 'Fruits & Vegetables' },
    { name: 'African nightshade', price: 'Ksh40/bunch', img: 'Images/African nightshade.jpg', category: 'Fruits & Vegetables' },
    { name: 'Oats', price: 'Ksh500/kg', img: 'Images/Oats.jpg', category: 'Pantry Staples' },
    { name: 'Eggs', price: 'Ksh180/dozen', img: 'Images/Dozen-Eggs.jpg', category: 'Dairy & Eggs' },
    { name: 'Grapes', price: 'Ksh0.86/grams', img: 'Images/Grapes.jpg', category: 'Fruits & Vegetables' },
    { name: 'Chicken', price: 'Ksh500/kg', img: 'Images/Chicken.jpg', category: 'Meat & Poultry' },
    { name: 'Mangoes', price: 'Ksh1.8/g', img: 'Images/Mangoes.jpg', category: 'Fruits & Vegetables' },
    { name: 'Chili Pepper', price: 'Ksh80/kg', img: 'Images/Chilli Pepper.jpg', category: 'Fruits & Vegetables' },
    { name: 'Okra', price: 'Ksh420/kg', img: 'Images/Okra.jpg', category: 'Fruits & Vegetables' },
    { name: 'Pawpaw', price: 'Ksh60/each', img: 'Images/Pawpaw.jpg', category: 'Fruits & Vegetables' },
    { name: 'Rice', price: 'Ksh150/kg', img: 'Images/Rice grains.jpg', category: 'Pantry Staples' },
    { name: 'Pork', price: 'Ksh750/kg', img: 'Images/Pork.jpg', category: 'Meat & Poultry' },
    { name: 'Kale', price: 'Ksh30/bunch', img: 'Images/Kale.jpg', category: 'Fruits & Vegetables' },
    { name: 'Butter', price: 'Ksh1500/kg', img: 'Images/Butter.jpg', category: 'Dairy & Eggs' },
    { name: 'Sweet Potatoes', price: 'Ksh4.99/lb', img: 'Images/Sweet Potatoes.jpg', category: 'Fruits & Vegetables' },
    { name: 'Jute Mallow', price: 'Ksh40/bunch', img: 'Images/Jute Mallow.jpg', category: 'Fruits & Vegetables' },
    { name: 'Lamb', price: 'Ksh1000/kg', img: 'Images/Lamb.jpg', category: 'Meat & Poultry' },
    { name: 'Green Beans', price: 'Ksh250/kg', img: 'Images/Green Beans.jpg', category: 'Fruits & Vegetables' }
];